### ISSUE TITLE
The result of F-measure was different

### ISSUE THREAD

**Issue by zicair** [nian-liu/PiCANet#3]
Hello, thank you for your code！

I used the model you provided to test on DUT-O dataset. But the value of F-β is 0.69, lower than your 0.79，The other two values are all right. I guess there is something wrong with my evaluation code. Could you provide the code of F-β code？

thanks a lot！

**Comment by nian-liu** [comment]
We used the max F-measure score, which is the max score under the optimal threshold (typically you need to compute all scores with varying the threshold and select the best one) instead of using a fixed threshold (usually twice of the mean salieny value).

**Comment by wb-finalking** [comment]
Hello, I used your pretrained caffemodel(resnet50-8s) without CRF to make an evaluation on ECSSD, my max F-measure is 0.918, but yours is 0.935. I used the different threshold(between 0 and 255) to calculate the F-measure result(256-vector of ECSSD dataset) to get the max value. Do I have something wrong ?
Thanks !

**Comment by nian-liu** [comment]
@wb-finalking Hi, this is because usually the F-measure codes implemented by different authors are slightly different, which will lead to slightly differnet scores. You can check some saliency paper to verify this. I implemented the F-measure code by myself.

However, this usually will not change the comparison result that A method is better/worse than B method. Furthermore, some metrics that have public implementations do not have this problem. e.g., the weighted F-measure used in my paper and the Structure-measure proposed in the papre "Structure-measure: A new way to evaluate foreground maps".
